### ISSUE TITLE
pip install lscae failed on Google Colab

### ISSUE THREAD

**Issue by ooghry** [jsvir/lscae#2]
Hello,
I'm trying to run your example on Google Colab, but I'm getting this error when installing from pip.
```
!pip install lscae
ERROR: Could not find a version that satisfies the requirement lscae (from versions: none)
ERROR: No matching distribution found for lscae
```
Any suggestion would be appreciated.

**Comment by jsvir** [comment]
Please use this command: `pip install -i https://test.pypi.org/simple/ lscae`

**Comment by ooghry** [comment]
@jsvir  It's work, thank you.
